# Generated by Django 6.0.1 on 2026-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('decription', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
