# Generated by Django 6.0.1 on 2026-01-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='test_name',
        ),
    ]
