# Generated by Django 6.0.1 on 2026-01-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_test_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
    ]
