# Generated by Django 6.0.1 on 2026-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_decription_test_description_alter_test_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
    ]
