# Generated by Django 6.0.1 on 2026-03-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_comprehensive_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
