# Generated by Django 6.0.1 on 2026-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_comprehensive_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
