# Generated by Django 6.0.1 on 2026-03-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
