# Generated by Django 6.0.1 on 2026-03-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
