# Generated by Django 6.0.1 on 2026-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_booking_ticket_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='ticket_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
