# Generated by Django 6.0.1 on 2026-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
