
# Generated by Django 6.0.1 on 2026-03-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_image_delete_image'),
        ('app', '0013_event_organizer'),
    ]

    operations = [
    ]
