# Generated by Django 6.0.1 on 2026-03-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ticket_code_from_checkin'),
        ('app', '0017_customer_role'),
    ]

    operations = [
    ]
