# Generated by Django 6.0.1 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_make_customer_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bakong', 'Bakong')], max_length=255),
        ),
    ]
