# Generated by Django 6.0.1 on 2026-04-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_invoice_user_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('event_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=255, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('USED', 'Used'), ('UNUSED', 'Unused')], default='UNUSED', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='app.booking')),
            ],
            options={
                'db_table': 'event_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
