# Generated by Django 6.0.1 on 2026-04-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_eventticket_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticket',
            old_name='event_ticket_id',
            new_name='id',
        ),
    ]
