# Generated by Django 6.0.1 on 2026-04-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_event_ticket_id_eventticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='app.booking'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('ALREADY_USED', 'Already Used'), ('INVALID', 'Invalid')], default='SUCCESS', max_length=20),
        ),
    ]
