# Generated by Django 6.0.1 on 2026-05-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_checkin_booking_alter_checkin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
    ]
